services:
  
  mongodb:
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=mongo'
      - 'MONGO_INITDB_ROOT_PASSWORD=mongo123'
      - 'MONGO_INITDB_DATABASE=cr_pharma_management'
    ports:
      - '27017:27017'
    volumes:
      - cr-dbdata:/data/db

volumes:
  cr-dbdata:
    driver: local